clear variables

current_location = './all_testing';
ds1 = read_and_unpermute(current_location, 48, 'sortvalues', true);

% current_location = '\';
current_location = './Yi_comparisons';
ds2 = read_and_unpermute(current_location, 12, 'sortvalues', true);

% current_location = '';
current_location = './zeta_sweep_R50/middle';
ds6 = read_and_unpermute(current_location, 48, 'sortvalues', true);

ds = combine_data_structures(ds1,ds2);

%% all curves plotted together

newcolors = ["#016D24","#FE6100","#DC267F","#648FFF","#1D0C6B","#27E0D8","#FFB000"];
colour_set_2 = ["#882255", "#AA4499", "#DDCC77", "#88CCEE", "#44AA99", "#117733", "#332288"];
colour_set_3 = ["#000000", "#2f2f2f", "#3c3c3c", "#515151", "#818181", "#c9c8c8", "#ececec"];
colour_set_4 = string(rgb2hex(repmat([1,1,1], [7,1]).*linspace(0,0.5, 7)'))';
colour_set_5 = ["#003f5c", "#374c80", "#7a5195", "#bc5090", "#ef5675", "#ff764a", "#ffa600"];

% slice = [56,   26,   1137,   357, 107];
% slice = [56,   26,  357, 107, 1440+3];
slice = [56, 1440+5, 107, 1440+3,  26];
% phi_vals = flip(deg2rad(linspace(0.01,179.9,150)));

ps = get_param_slices(ds, slice);

% %% analyse data from each, we want local minima and maxima and end points.
E_input = ds.E_all_nonlinear;
outputs_analyse = analyse_phi_curve(E_input,ds, slice, ds.phi_vals,...
    'PlotCurves', false, 'IgnoreNearNaN', false);

f5 = plot_phi_curves(ds, slice, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,'PlotLocalMinima', true,...
    'ColorOrder', newcolors, 'RelativeEnergy', true,'ylabel','$\Delta E/\mathrm{max}(|\Delta E|)$',...
    'DisplayNameIndex',12);
axes1 = gca;
% axes1.

outputs_analyse = analyse_phi_curve(ds6.E_all_nonlinear,ds6, 60, ds6.phi_vals,...
    'PlotCurves', false, 'IgnoreNearNaN', false);
f5 = plot_phi_curves(ds6, 60, ds6.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,'PlotLocalMinima', true,...
    'ColorOrder', newcolors(6:7), 'RelativeEnergy', true,'ylabel','$\Delta E/\mathrm{max}(|\Delta E|)$',...
    'DisplayNameIndex',12,'FigureHandle', f5);


%% individual shapes at minima

outputs_analyse = analyse_phi_curve(E_input,ds, slice, ds.phi_vals,...
    'PlotCurves', false, 'IgnoreNearNaN', false);
counter = 0;
for index=slice
    counter = counter+1;
    R = ds.parameter_set(index,4);
    d = ds.parameter_set(index,3);
    phi = outputs_analyse.phi_at_min(counter);
    kappa = ds.parameter_set(index,6);
    Sigma = outputs_analyse.Sigma_at_min(counter);
    plot_shape_no_axis(R, d, phi, kappa, Sigma, 'colour', newcolors(counter))
end

%% curve type 1 - Fully Wrapped
index = 56;
anno_string = [sprintf('$k_D = %0.2g$ pJ/$\\mu$m$^2$ \n', ds.parameter_set(index,5)),...
    sprintf('$\\kappa = %0.2g$ pJ \n', ds.parameter_set(index,6)),...
    sprintf('$R = %0.2g$ $\\mu$m \n', ds.parameter_set(index,4)),...
    sprintf('$\\alpha_i = %0.2g$ \n', ds.parameter_set(index,7)),...
    sprintf('$\\zeta = %0.2g$ \n', -ds.parameter_set(index,1)/ds.parameter_set(index,5)),...
    sprintf('$\\sigma = %0.2g$ \n', pi*ds.parameter_set(index,4)^2/ds.parameter_set(index,3)^2)];
outputs_analyse = analyse_phi_curve(ds.E_all_nonlinear,ds, index, ds.phi_vals,...
    'PlotCurves', false, 'IgnoreNearNaN', false);
f24 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','AnnotationString', anno_string,...
    'ExtraCurveIndex', 0, 'AnalyticalCurves', [1,2],'PlotLocalMinima', true);
f24 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$',...
    'ExtraCurveIndex', 1, 'PlotCurves', [1,3,4,6],'PlotLocalMinima', true);
f24 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$',...
    'ExtraCurveIndex', 5, 'PlotCurves', [1,2,5],'PlotLocalMinima', true,...
    'ColorOrder', colour_set_5, 'HighTensionApprox', true,...
    'aBaA_Approx', false);

%% curve type 2 - Full/partial at full
index = 1440+5;
outputs_analyse = analyse_phi_curve(ds.E_all_nonlinear,ds, index, ds.phi_vals,...
    'PlotCurves', false, 'IgnoreNearNaN', false);
anno_string = [sprintf('$k_D = %0.2g$ pJ/$\\mu$m$^2$, ', ds.parameter_set(index,5)),...
    sprintf('$\\kappa = %0.2g$ pJ \n', ds.parameter_set(index,6)),...
    sprintf('$R = %0.2g$ $\\mu$m, ', ds.parameter_set(index,4)),...
    sprintf('$\\alpha_i = %0.2g$ \n', ds.parameter_set(index,7)),...
    sprintf('$\\zeta = %0.2g$ \n', -ds.parameter_set(index,1)/ds.parameter_set(index,5)),...
    sprintf('$\\sigma = %0.2g$ \n', pi*ds.parameter_set(index,4)^2/ds.parameter_set(index,3)^2)];
f26 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','AnnotationString', anno_string,...
    'ExtraCurveIndex', 0, 'AnalyticalCurves', [1,2,3],'PlotLocalMinima', true);
f26 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$',...
    'ExtraCurveIndex', 3, 'PlotCurves', [1,3,6],'PlotLocalMinima', true);
f26 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$',...
    'ExtraCurveIndex', 6, 'PlotCurves', [1,4,6],'PlotLocalMinima', true,...
    'ColorOrder', colour_set_5, 'HighTensionApprox', true,...
    'aBaA_Approx', false);

f101 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','AnnotationString', anno_string,...
    'AnalyticalCurves', [5],'PlotLocalMinima', true, ...
    'PlotCurves', [1,4,6]);
f102 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','AnnotationString', anno_string,...
    'AnalyticalCurves', [5],'PlotLocalMinima', true, ...
    'PlotCurves', [1,4,6], 'PlotRelative', true);
ylim([-1.1,1.1])

%% curve type 3 - Full/partial at partial
index = 107;
outputs_analyse = analyse_phi_curve(ds.E_all_nonlinear,ds, index, ds.phi_vals,...
    'PlotCurves', false, 'IgnoreNearNaN', false);
anno_string = [sprintf('$k_D = %0.2g$ pJ/$\\mu$m$^2$ \n', ds.parameter_set(index,5)),...
    sprintf('$\\kappa = %0.2g$ pJ \n', ds.parameter_set(index,6)),...
    sprintf('$R = %0.2g$ $\\mu$m \n', ds.parameter_set(index,4)),...
    sprintf('$\\alpha_i = %0.2g$ \n', ds.parameter_set(index,7)),...
    sprintf('$\\zeta = %0.2g$ \n', -ds.parameter_set(index,1)/ds.parameter_set(index,5)),...
    sprintf('$\\sigma = %0.2g$ \n', pi*ds.parameter_set(index,4)^2/ds.parameter_set(index,3)^2)];
f32 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','AnnotationString', anno_string,...
    'ExtraCurveIndex', 0, 'AnalyticalCurves', [1,2],'PlotLocalMinima', true);
f32 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$',...
    'ExtraCurveIndex', 3, 'PlotCurves', [1,3,6],'PlotLocalMinima', true);
f32 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','ColorOrder', colour_set_5,...
    'ExtraCurveIndex', 6, 'PlotCurves', [1,4,6],'PlotLocalMinima', true,...
    'aBaA_Approx', false,'HighTensionApprox', true);

%% curve type 4 - unwrapped/partial at unwrapped
index = 1440+3;
outputs_analyse = analyse_phi_curve(ds.E_all_nonlinear,ds, index, ds.phi_vals,...
    'PlotCurves', false, 'IgnoreNearNaN', false);
anno_string = [sprintf('$k_D = %0.2g$ pJ/$\\mu$m$^2$ \n', ds.parameter_set(index,5)),...
    sprintf('$\\kappa = %0.2g$ pJ \n', ds.parameter_set(index,6)),...
    sprintf('$R = %0.2g$ $\\mu$m \n', ds.parameter_set(index,4)),...
    sprintf('$\\alpha_i = %0.2g$ \n', ds.parameter_set(index,7)),...
    sprintf('$\\zeta = %0.2g$ \n', -ds.parameter_set(index,1)/ds.parameter_set(index,5)),...
    sprintf('$\\sigma = %0.2g$ \n', pi*ds.parameter_set(index,4)^2/ds.parameter_set(index,3)^2)];
f32 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','AnnotationString', anno_string,...
    'ExtraCurveIndex', 0, 'AnalyticalCurves', [1,2],'PlotLocalMinima', true);
f32 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','PlotLocalMinima', true,...
    'ExtraCurveIndex', 3, 'PlotCurves', [1,3,6]);
f32 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','ColorOrder', colour_set_5,...
    'ExtraCurveIndex', 6, 'PlotCurves', [1,4,6],'PlotLocalMinima', true,...
    'aBaA_Approx', false,'HighTensionApprox', true);
ylim([-5e-7, 20e-7])

%% curve type 5 - unwrapped
index = 26;
outputs_analyse = analyse_phi_curve(ds.E_all_nonlinear,ds, index, ds.phi_vals,...
    'PlotCurves', false, 'IgnoreNearNaN', false);
anno_string = [sprintf('$k_D = %0.2g$ pJ/$\\mu$m$^2$ \n', ds.parameter_set(index,5)),...
    sprintf('$\\kappa = %0.2g$ pJ \n', ds.parameter_set(index,6)),...
    sprintf('$R = %0.2g$ $\\mu$m, ', ds.parameter_set(index,4)),...
    sprintf('$\\alpha_i = %0.2g$ \n', ds.parameter_set(index,7)),...
    sprintf('$\\zeta = %0.2g$, ', -ds.parameter_set(index,1)/ds.parameter_set(index,5)),...
    sprintf('$\\sigma = %0.2g$ \n', pi*ds.parameter_set(index,4)^2/ds.parameter_set(index,3)^2)];
f32 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','AnnotationString', anno_string,...
    'ExtraCurveIndex', 0, 'AnalyticalCurves', [1,2],'PlotLocalMinima', true);
f32 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$',...
    'ExtraCurveIndex', 1, 'PlotCurves', [1,3,4,6],'PlotLocalMinima', true,...
    'aBaA_Approx', true);
f32 = plot_phi_curves_all(ds, index, ds.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','ColorOrder', colour_set_5,...
    'ExtraCurveIndex', 7, 'PlotCurves', [1,2,5],'PlotLocalMinima', true,...
    'aBaA_Approx', false,'HighTensionApprox', true);

%% curve type 6 ???
index = 60;
outputs_analyse = analyse_phi_curve(ds6.E_all_nonlinear,ds6, index, ds6.phi_vals,...
    'PlotCurves', false, 'IgnoreNearNaN', false);
anno_string = [sprintf('$k_D = %0.2g$ pJ/$\\mu$m$^2$ \n', ds6.parameter_set(index,5)),...
    sprintf('$\\kappa = %0.2g$ pJ \n', ds6.parameter_set(index,6)),...
    sprintf('$R = %0.2g$ $\\mu$m, ', ds6.parameter_set(index,4)),...
    sprintf('$\\alpha_i = %0.2g$ \n', ds6.parameter_set(index,7)),...
    sprintf('$\\zeta = %0.2g$, ', -ds6.parameter_set(index,1)/ds6.parameter_set(index,5)),...
    sprintf('$\\sigma = %0.2g$ \n', pi*ds6.parameter_set(index,4)^2/ds6.parameter_set(index,3)^2)];
f66 = plot_phi_curves_all(ds6, index, ds6.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','AnnotationString', anno_string,...
    'ExtraCurveIndex', 0, 'AnalyticalCurves', [1,2],'PlotLocalMinima', true);
f666 = plot_phi_curves_all(ds6, index, ds6.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$',...
    'ExtraCurveIndex', 3, 'PlotCurves', [1,3,6],'PlotLocalMinima', true);
f6666 = plot_phi_curves_all(ds6, index, ds6.phi_vals,...
    'AnalysisData', outputs_analyse,'PlotMinima', true,...
    'ylabel','$\Delta E$','ColorOrder', colour_set_5,...
    'ExtraCurveIndex', 6, 'PlotCurves', [1,4,6],'PlotLocalMinima', true,...
    'aBaA_Approx', false,'HighTensionApprox', true);
ylim([-0.5e-7, 2e-7])



%% construct slices, can't really be done in a separate function
% generate list of independent variables to run, which should be in the
% order [epsilon, n0, d, R, kD, kappa, alpha_i] for each row
R_vals = [0.05,0.5];                 % um
sigma_vals = logspace(-6,-2,12);                % surface fraction
%d_vals = sqrt(R_vals.^2./sigma_vals);           % um
kD_vals = 300/10^12*1e9;                        % picoJ/um^2
kD_base = 300/10^12*1e9;                        % picoJ/um^2
zeta_vals = logspace(-6,-3,12);                  % dimensionless
epsilon_vals = -zeta_vals*kD_base;              % picoJ/um^2
n0_vals = 1;                                    % fraction
kappa_vals = 1e-19*1e12;         % picoJ
% kappa_vals = logspace(-21,-15, 60)*1e12;
alpha_i_vals = [1e-6,1e-5,1e-4,1e-3,1e-2];                            % fraction
phi_vals = flip(deg2rad(linspace(0.01,179.9,150)));
% other constants
N = 3e5;
color_number = 5;

ii = 0;
slice = [];
for rr = 1:length(R_vals)
    for ss = 1:length(sigma_vals)
        for kk = 1:length(kD_vals)
            for ee = 1:length(epsilon_vals)
                for nn = 1:length(n0_vals)
                    for pp = 1:length(kappa_vals)
                        for aa = 1:length(alpha_i_vals)
                            ii = ii+1;
%                             if ee==12 && aa==1 && rr==1 && ss == 1
%                                 slice = [slice, ii];
%                             end
%                             if any(ee==[6,12]) && aa==1 && rr==1 && ss == 1
%                                 slice = [slice, ii];
%                             end
%                             if ee==6 && aa==1 && rr==1 && ss == 1
%                                 slice = [slice, ii];
%                             end
%                             if ee==12 && aa==2 && rr==2 && ss == 7
%                                 slice = [slice, ii];
%                             end
                            if ee==10 && aa==2 && rr==1 && any(ss==[1,2,4,10])
                                slice = [slice, ii];
                            end

                        end
                    end
                end
            end
        end
    end
end
size_params = size(ds.parameter_set);